### ISSUE TITLE
brew.sh would be nice 

### ISSUE THREAD

**Issue by ghost** [Staffbase/retrace#108]
A package for brew.sh would be nice :)

**Comment by ice8lue** [comment]
Ya, will be the next thing I'll do ;)

**Comment by flaxel** [comment]
You can use the [Brew Test Bot](https://docs.brew.sh/Brew-Test-Bot) to do automated reviews and testings.

**Comment by ice8lue** [comment]
Brew PR is up: https://github.com/Homebrew/homebrew-cask/pull/115138

**Comment by ice8lue** [comment]
You may use `brew install ice8lue/homebrew-taps/re-trace` to install or `brew tap ice8lue/homebrew-taps` and then `brew install re-trace`.
