### ISSUE TITLE
Define custom shortcut

### ISSUE THREAD

**Issue by ghost** [Staffbase/retrace#109]
I might have just missed the option to do it, but cmd+l is also my most used shortcut in almost every browser, so I would really like to define a different shortcut for a retrace.

**Comment by ice8lue** [comment]
You can actually do that already (though there is no UI for that so far). Edit `~/Library/Application\ Support/RE-Trace/config.json` and adjust the "floatShortcut" property. After restart, the new shortcut will work 👍

**Comment by ofcourseican** [comment]
Uh, nice. Thanks. 

I still think that cmd+l is not the best default ;)

**Comment by ice8lue** [comment]
Up for discussion ;)
